version: '3.7'

volumes:
  node_modules:

services:
  app:
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=dev
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/node/app/
      - /home/node/.npm
      - node_modules:/home/node/app/node_modules

  test_e2e:
    build:
      context: .
      target: dev
    environment:
      - LAUNCH_URL=http://app:8080
      - SELENIUM_HOST=selenium-chrome
      - SELENIUM_PORT=4444
    # Todo: Maybe improve this by adding a script to wait for app and selinium
    command: "sh -c 'sleep 5 && npm run test:e2e -- --url http://app:8080'"
    volumes:
      - ./:/home/node/app
      - /home/node/.npm
      - node_modules:/home/node/app/node_modules
    depends_on:
      - app
      - selenium-chrome

  selenium-chrome: #Docs: https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneChrome
    image: selenium/standalone-chrome
    expose:
      - 4444
    # ports:
    # - '5900:5900' # expose debug port if needed
