version: '3.7'

volumes:
  node_modules:

services:
  app:
    command: 'sh -c "npm start"'
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=dev
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DBNAME}
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./:/home/node/app/
      - /home/node/.npm
    depends_on:
      # - app-client
      - mongo

  # app-client:
  #   command: 'sh -c "echo hello-world && npm run serve"'
  #   build:
  #     context: .
  #     target: dev
  #   environment:
  #       - NODE_ENV=dev
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - './:/home/node/app/'
  #     - /home/node/.npm

  mongo:
    build: ./mongo/
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_DBNAME
      - MONGO_USERNAME
      - MONGO_PASSWORD

  # test_e2e:
  #   build:
  #     context: .
  #     target: dev
  #   environment:
  #     - LAUNCH_URL=http://app:8080
  #     - SELENIUM_HOST=selenium-chrome
  #     - SELENIUM_PORT=4444
  #   # Todo: Maybe improve this by adding a script to wait for app and selinium
  #   command: "sh -c 'sleep 5 && npm run test:e2e -- --url http://app:8080'"
  #   volumes:
  #     - ./:/home/node/app
  #     - /home/node/.npm
  #     - node_modules:/home/node/app/node_modules
  #   depends_on:
  #     - app
  #     - selenium-chrome

  # selenium-chrome: #Docs: https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneChrome
  #   image: selenium/standalone-chrome
  #   expose:
  #     - 4444
  #   ports:
  #   - '5900:5900' # expose debug port if needed
